#!/usr/bin/env bash
set -e

red='\033[0;31m'
green='\033[0;32m'
yellow='\033[0;33m'
neutral='\033[0m'

printf ${neutral}"Starting installation\n"

# perform some very rudimentary platform detection
case "$(uname)" in
	Linux)
		printf ${yellow}"TODO: Ubuntu installation\n"
		;;
	Darwin)
		printf ${green}"Installing brew\n"
		/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
		
		if ! command -v git >/dev/null 2>&1 
		then
			printf ${green}"Installing git via brew\n"
			brew install git
		fi

		if ! command -v python >/dev/null 2>&1 
		then
			printf ${green}"Installing python via brew\n"
			brew install python
		fi

		if ! command -v ansible >/dev/null 2>&1 
		then
			printf ${green}"Installing ansible via brew\n"
			sudo pip install ansible
		fi
		;;
esac

exit 0
#  WindowsNT)
#    $sh_c "$curl $url/$version/fn.exe"
#    # TODO how to make executable? chmod? how to do tmp file and move?
#    fn.exe --version
#    ;;
#  *)
#    cat >&2 <<'EOF'
#
#  Either your platform is not easily detectable or is not supported by this
#  installer script (yet - PRs welcome! [fn/install]).
#  Please visit the following URL for more detailed installation instructions:
#
#    https://github.com/fnproject/fn
#
#EOF
#    exit 1
#esac
# TODO:
# Install curl
# Install git
# Install sublime text 3
# Install spotify
# Install google chrome
# Install dropbox
# Install skype
# Updated daemon.json with dns and insecure registries
# Install docker-sync

command -v git >/dev/null 2>&1 || { echo >&2 "I require git.  Aborting."; exit 1; }

printf "Installing Ansible\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/ansible?no_cache=$RANDOM | sudo sh
printf "Installing Docker\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/docker?no_cache=$RANDOM | sudo sh
printf "Installing gitprune\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/gitprune?no_cache=$RANDOM -o /usr/local/bin/gitprune && sudo chmod +x /usr/local/bin/gitprune
printf "Installing daker\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/daker?no_cache=$RANDOM -o /usr/local/bin/daker && sudo chmod +x /usr/local/bin/daker
printf "Installing daker composer\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/daker_c?no_cache=$RANDOM -o /usr/local/bin/daker_c && sudo chmod +x /usr/local/bin/daker_c
printf "Installing daker phpqatools\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/daker_p?no_cache=$RANDOM -o /usr/local/bin/daker_p && sudo chmod +x /usr/local/bin/daker_p
printf "Installing daker with apache\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/daker_a?no_cache=$RANDOM -o /usr/local/bin/daker_a && sudo chmod +x /usr/local/bin/daker_a
printf "Installing update software\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/update_software?no_cache=$RANDOM -o /usr/local/bin/update_software && sudo chmod +x /usr/local/bin/update_software

printf "Installing docker-workspace\n"
bash <(curl https://raw.githubusercontent.com/travis-south/docker-workspace/master/install?no_cache=$RANDOM)

printf "Setting up machine\n"
rm -rf ansible-playbook-setup-machine
git clone https://github.com/travis-south/ansible-playbook-setup-machine.git
cd ansible-playbook-setup-machine
ansible-galaxy install -r requirements.yml
ansible-playbook main.yml -i inventory -K
