#!/usr/bin/env bash
set -e

# perform some very rudimentary platform detection
#case "$(uname)" in
#  Linux)
#    $sh_c "$curl /tmp/fn_linux $url/$version/fn_linux"
#    $sh_c "mv /tmp/fn_linux /usr/local/bin/fn"
#    $sh_c "chmod +x /usr/local/bin/fn"
#    fn --version
#    ;;
#  Darwin)
#    $sh_c "$curl /tmp/fn_mac $url/$version/fn_mac"
#    $sh_c "mv /tmp/fn_mac /usr/local/bin/fn"
#    $sh_c "chmod +x /usr/local/bin/fn"
#    fn --version
#    ;;
#  WindowsNT)
#    $sh_c "$curl $url/$version/fn.exe"
#    # TODO how to make executable? chmod? how to do tmp file and move?
#    fn.exe --version
#    ;;
#  *)
#    cat >&2 <<'EOF'
#
#  Either your platform is not easily detectable or is not supported by this
#  installer script (yet - PRs welcome! [fn/install]).
#  Please visit the following URL for more detailed installation instructions:
#
#    https://github.com/fnproject/fn
#
#EOF
#    exit 1
#esac
# TODO:
# Install curl
# Install git
# Install sublime text 3
# Install spotify
# Install google chrome
# Install dropbox
# Install skype

command -v git >/dev/null 2>&1 || { echo >&2 "I require git.  Aborting."; exit 1; }

printf "Installing Ansible\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/ansible?no_cache=$RANDOM | sudo sh
printf "Installing Docker\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/docker?no_cache=$RANDOM | sudo sh
printf "Installing gitprune\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/gitprune?no_cache=$RANDOM -o /usr/local/bin/gitprune && sudo chmod +x /usr/local/bin/gitprune
printf "Installing daker\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/daker?no_cache=$RANDOM -o /usr/local/bin/daker && sudo chmod +x /usr/local/bin/daker
printf "Installing daker composer\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/daker_c?no_cache=$RANDOM -o /usr/local/bin/daker_c && sudo chmod +x /usr/local/bin/daker_c
printf "Installing daker phpqatools\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/daker_p?no_cache=$RANDOM -o /usr/local/bin/daker_p && sudo chmod +x /usr/local/bin/daker_p
printf "Installing daker with apache\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/daker_a?no_cache=$RANDOM -o /usr/local/bin/daker_a && sudo chmod +x /usr/local/bin/daker_a
printf "Installing update software\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/update_software?no_cache=$RANDOM -o /usr/local/bin/update_software && sudo chmod +x /usr/local/bin/update_software

printf "Installing docker-workspace\n"
sudo curl -LSs https://raw.githubusercontent.com/travis-south/shinst/master/ws?no_cache=$RANDOM -o /usr/local/bin/ws && sudo chmod +x /usr/local/bin/ws

printf "Setting up machine\n"
rm -rf ansible-playbook-setup-machine
git clone https://github.com/travis-south/ansible-playbook-setup-machine.git
cd ansible-playbook-setup-machine
ansible-galaxy install -r requirements.yml
ansible-playbook main.yml -i inventory -K
