#!/usr/bin/env bash

set -e

command -v daker >/dev/null 2>&1 || { echo >&2 "I require daker but it's not installed.  Aborting."; exit 1; }

docker pull travissouth/phpqatools

daker travissouth/phpqatools $@
