#!/usr/bin/env bash

set -e

command -v docker >/dev/null 2>&1 || { echo >&2 "I require docker but it's not installed.  Aborting."; exit 1; }

mkdir -p $HOME/.cache/composer
chmod -R 777 $HOME/.cache/composer

rm -rf $HOME/.docker-temp-ssh
cp -dpR $HOME/.ssh $HOME/.docker-temp-ssh
rm -rf $HOME/.docker-temp-ssh/config

eval $(ssh-agent) > /dev/null
ssh-add <(cat $HOME/.docker-temp-ssh/id_rsa)

docker run --rm -ti -v $(pwd):/app -v $(pwd):/var/www/html/app -v $SSH_AUTH_SOCK:/ssh-auth.sock -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v $HOME/.docker-temp-ssh:/home/$USER/.ssh:ro -v $HOME/.cache/composer:/tmp/cache --user $(id -u):$(id -g) --env SSH_AUTH_SOCK=/ssh-auth.sock $@

# docker run -d -p 8080:80 --name php-app -v "$PWD":/var/www/html php:7.1.8-apache
